### PR TITLE
[MINT-172] Update script and style tags to use CSP nonces

### PR DESCRIPTION
**Pull request by exonjoe**
Used in the web CSP tickets (e.g. https://github.com/eatclub/web/pull/6530) to enable us to pass nonces down to these templates as required.

### CODE REVIEW

**Comment by llostris** [comment]
@exonjoe Looks good to me. Is this going to affect any specific templates so it can be tested? It looks like we've still got some errors in Django Admin, and those are meant to be handled with https://eatclub.atlassian.net/browse/COM-782?

**Review by sanchojaf — APPROVED** [review]

**Review by lceatclub — APPROVED** [review]
LGTM

**Comment by llostris** [comment]
@exonjoe Any reason we didn't merge this? :) We have some upcoming changes to the repo, so it would be good to merge this to master.

**Review by llostris — APPROVED** [review]
Sorry about PROD-72 ending up on this branch!

PROD-72 have been tested by me and are approved

**Comment by exonjoe** [comment]
> @exonjoe Any reason we didn't merge this? :) We have some upcoming changes to the repo, so it would be good to merge this to master.

Yeah, not to my recollection! I just took another look and it all seems good. Merged!

**Pull request merged**
